name = "v3api"
main = "src/index.ts"
compatibility_date = "2025-02-20"

[[r2_buckets]]
binding = "dataapi"
bucket_name = "dataapi"

[[d1_databases]]
binding = "DB"
database_name = "v4api-users"
database_id = "c958fd3c-484c-4be4-82ed-195115feb0d8"
